# Generated by Django 3.1.7 on 2021-04-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210409_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='listing',
            field=models.ManyToManyField(null=True, related_name='watched', to='auctions.Listing'),
        ),
    ]
