# Generated by Django 3.1.7 on 2021-04-12 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210409_1432'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
